// Compiles the EDITH source files into lib/edith/content.generated.ts.
//
//   npm run edith:build   — regenerate after editing either source file
//   npm run edith:check   — fail if the generated file is stale (tests run this)
//
// Sources (the only place copy and sequence logic live):
//   automations/edith/edith-automations.yaml
//   automations/edith/EDITH_Email_Sequences.md
//
// The build fails when the two disagree: a template_id the manifest uses with
// no template, or a {{merge_field}} the engine can't fill. Quality-gate checks
// from the .md (subject length, prices before Sequence 5, one link) are
// reported as warnings, never auto-fixed: copy is locked upstream.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { pathToFileURL } from "node:url";
import { createHash } from "node:crypto";
import YAML from "yaml";
import { KNOWN_FIELDS } from "../../lib/edith/engine.ts";

const root = new URL("../../", import.meta.url);
const read = (p) => readFileSync(new URL(p, root), "utf8").replace(/\r\n/g, "\n");
const OUT = new URL("lib/edith/content.generated.ts", root);

export function compile() {
  const yamlSrc = read("automations/edith/edith-automations.yaml");
  const mdSrc = read("automations/edith/EDITH_Email_Sequences.md");
  const manifest = YAML.parse(yamlSrc);
  const templates = parseTemplates(mdSrc);
  const errors = [];
  const warnings = [];

  // Every template the manifest can send must exist.
  const needed = new Set();
  for (const seq of manifest.sequences) {
    for (const st of seq.steps) {
      needed.add(st.template_id);
      if (st.variant) needed.add(st.variant.template_id);
      if (st.then?.reminder) needed.add(st.then.reminder.template_id);
    }
  }
  for (const id of needed) if (!templates[id]) errors.push(`manifest uses template "${id}" but EDITH_Email_Sequences.md has no "### EMAIL ${id}" block`);
  for (const id of Object.keys(templates)) if (!needed.has(id)) warnings.push(`template ${id} exists in the .md but no sequence step sends it`);

  // Every merge field must be one the engine knows how to fill.
  for (const t of Object.values(templates)) {
    for (const f of t.merge_fields_used) if (!KNOWN_FIELDS.includes(f)) errors.push(`template ${t.template_id} uses {{${f}}}, which the engine can't fill`);
    if (!t.subject) errors.push(`template ${t.template_id} has no Subject line`);
    if (!t.body) errors.push(`template ${t.template_id} has no body`);
  }
  for (const f of manifest.global_rules.merge_field_holds) if (!KNOWN_FIELDS.includes(f)) errors.push(`merge_field_holds names "${f}", which the engine doesn't know`);

  // Quality gate (from the .md) — reported, not enforced.
  for (const t of Object.values(templates)) {
    if (t.subject.length > 50) warnings.push(`${t.template_id}: subject is ${t.subject.length} characters before merge (gate: under 50)`);
    // $77 is the Omaha receipt (allowed); the offer prices are not.
    if (/^[1-4]-/.test(t.template_id) && /\$\s?(997|250|747)\b/.test(t.body + t.subject)) warnings.push(`${t.template_id}: an offer price appears in Sequences 1-4`);
    const links = (t.body.match(/\{\{\s*\w+_link\s*\}\}/g) || []).length;
    if (links > 1 && t.template_id !== "7-1") warnings.push(`${t.template_id}: ${links} links in the body (gate: one CTA)`);
  }

  if (errors.length) throw new Error("EDITH build failed:\n  - " + errors.join("\n  - "));
  const content = {
    manifest,
    templates,
    signature: String(manifest.sender.signature_block || "").trimEnd(),
    source_hash: createHash("sha256").update(yamlSrc).update("\0").update(mdSrc).digest("hex").slice(0, 16),
    warnings,
  };
  const ts =
    "// AUTO-GENERATED by scripts/edith/build.mjs from automations/edith/*.\n" +
    "// Do not edit by hand: change the source files and run `npm run edith:build`.\n" +
    'import type { EdithContent } from "./engine";\n\n' +
    "export const CONTENT: EdithContent = " + JSON.stringify(content, null, 2) + ";\n";
  return { ts, content };
}

// "### EMAIL 1-1 — Cold open" + a fenced header block (Trigger / Subject line /
// Preview text) + the body + a fenced footer block (CTA / Internal note).
function parseTemplates(md) {
  const out = {};
  const lines = md.split("\n");
  let i = 0;
  while (i < lines.length) {
    const h = /^### EMAIL (\S+)\s+—\s+(.+)$/.exec(lines[i]);
    if (!h) { i++; continue; }
    const [, id, title] = h;
    let j = i + 1;
    const block = [];
    while (j < lines.length && !/^#{2,3} /.test(lines[j]) && lines[j] !== "---") block.push(lines[j++]);
    i = j;
    const fences = [];
    block.forEach((l, k) => { if (/^```/.test(l)) fences.push(k); });
    if (fences.length < 4) throw new Error(`EDITH build: template ${id} needs a header fence and a CTA fence`);
    const head = kv(block.slice(fences[0] + 1, fences[1]));
    const foot = kv(block.slice(fences[2] + 1, fences[3]));
    const body = block.slice(fences[1] + 1, fences[2]).join("\n").replace(/^\n+|\n+$/g, "");
    const subject = head["Subject line"] || "";
    const preview = head["Preview text"] || "";
    const fields = new Set();
    for (const m of (subject + "\n" + preview + "\n" + body).matchAll(/\{\{\s*(\w+)\s*\}\}/g)) fields.add(m[1]);
    out[id] = {
      template_id: id,
      title: title.trim(),
      trigger: head["Trigger"] || "",
      subject,
      preview_text: preview,
      body,
      cta: foot["CTA"] || "",
      internal_note: foot["Internal note"] || "",
      merge_fields_used: [...fields],
    };
  }
  return out;
}

function kv(lines) {
  const o = {};
  let last = null;
  for (const l of lines) {
    const m = /^([A-Za-z][A-Za-z ]*?):\s+(.*)$/.exec(l);
    if (m) { last = m[1].trim(); o[last] = m[2].trim(); }
    else if (last && l.trim()) o[last] += " " + l.trim();
  }
  return o;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const { ts, content } = compile();
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8").replace(/\r\n/g, "\n") : "";
  if (process.argv.includes("--check")) {
    if (current !== ts) { console.error("lib/edith/content.generated.ts is stale — run `npm run edith:build`."); process.exit(1); }
    console.log(`EDITH content is current (${Object.keys(content.templates).length} templates, source ${content.source_hash}).`);
  } else {
    writeFileSync(OUT, ts);
    console.log(`Wrote lib/edith/content.generated.ts — ${Object.keys(content.templates).length} templates, ${content.manifest.sequences.length} sequences, source ${content.source_hash}.`);
  }
  for (const w of content.warnings) console.log("  quality gate: " + w);
}
