// AUTO-GENERATED by scripts/edith/build.mjs from automations/edith/*.
// Do not edit by hand: change the source files and run `npm run edith:build`.
import type { EdithContent } from "./engine";

export const CONTENT: EdithContent = {
  "manifest": {
    "version": 1,
    "sender": {
      "name": "EDITH at Creative Impact",
      "from": "edith@creativeimpactmedia.co",
      "reply_to": "hello@creativeimpactmedia.co",
      "signature_block": "EDITH\nCreative Impact · Emmanuel's assistant — the AI kind. A human reads every reply.\nhello@creativeimpactmedia.co\n"
    },
    "global_rules": {
      "timezone": "America/New_York",
      "send_window": {
        "start": "08:00",
        "end": "18:00",
        "days": [
          "Mon",
          "Tue",
          "Wed",
          "Thu",
          "Fri",
          "Sat"
        ]
      },
      "max_emails_per_contact_per_24h": 1,
      "stop_on": [
        {
          "event": "email.replied",
          "route_to": "emmanuel_inbox"
        },
        {
          "event": "call.booked"
        },
        {
          "event": "deposit.paid"
        },
        {
          "event": "contact.unsubscribed"
        },
        {
          "tag": "do_not_contact"
        }
      ],
      "merge_field_holds": [
        "specific_detail",
        "q5_answer",
        "not_fit_reason",
        "what_would_change",
        "reach_number",
        "reach_screenshot"
      ],
      "compliance": {
        "physical_address_footer_on": [
          "SEQ1"
        ],
        "unsubscribe_footer_on": [
          "SEQ1",
          "SEQ7"
        ]
      },
      "approval": {
        "templates_locked": true,
        "live_send_requires_flag": "edith_live"
      }
    },
    "events": [
      "contact.created",
      "lead.form_submitted",
      "call.booked",
      "call.no_show",
      "call.completed",
      "deposit.paid",
      "balance.paid",
      "cut.delivered",
      "cut.approved",
      "episode.published",
      "promo.started",
      "promo.ended",
      "board.updated"
    ],
    "contact_fields": {
      "required_for_cold": [
        "first_name",
        "business_name",
        "neighborhood",
        "specific_detail"
      ],
      "computed": {
        "spots_remaining": "live count from board; 0 triggers SEQ2/2-4 variant"
      },
      "tags": [
        "cold_prospect",
        "cold_closed",
        "inbound",
        "booked",
        "no_show",
        "undecided",
        "not_fit",
        "client",
        "cut_approved",
        "nurture",
        "do_not_contact"
      ]
    },
    "sequences": [
      {
        "id": "SEQ1",
        "name": "Cold first touch",
        "enroll_on": {
          "event": "contact.created",
          "when": {
            "tag": "cold_prospect",
            "specific_detail": "not_empty"
          }
        },
        "exit_on": [
          "email.replied",
          "call.booked",
          "do_not_contact"
        ],
        "steps": [
          {
            "step": "1-1",
            "template_id": "1-1",
            "delay": "0d",
            "anchor": "enroll"
          },
          {
            "step": "1-2",
            "template_id": "1-2",
            "delay": "3d",
            "anchor": "enroll"
          },
          {
            "step": "1-3",
            "template_id": "1-3",
            "delay": "7d",
            "anchor": "enroll"
          }
        ],
        "on_complete": {
          "set_tag": "cold_closed"
        },
        "reply_routing": {
          "later": {
            "set_tag": "nurture",
            "enroll": "SEQ7"
          },
          "default": "emmanuel_inbox"
        }
      },
      {
        "id": "SEQ2",
        "name": "Inbound lead, no call booked",
        "enroll_on": {
          "event": "lead.form_submitted",
          "unless_within": {
            "event": "call.booked",
            "minutes": 10
          }
        },
        "exit_on": [
          "call.booked",
          "email.replied",
          "deposit.paid"
        ],
        "side_effects_on_enroll": [
          {
            "create_task": {
              "assignee": "emmanuel",
              "title": "Call {{business_name}} — speed to lead",
              "due": "+60m"
            }
          }
        ],
        "steps": [
          {
            "step": "2-1",
            "template_id": "2-1",
            "delay": "5m",
            "anchor": "enroll",
            "ignore_send_window": false
          },
          {
            "step": "2-2",
            "template_id": "2-2",
            "delay": "1d",
            "anchor": "enroll"
          },
          {
            "step": "2-3",
            "template_id": "2-3",
            "delay": "3d",
            "anchor": "enroll"
          },
          {
            "step": "2-4",
            "template_id": "2-4",
            "delay": "6d",
            "anchor": "enroll",
            "variant": {
              "when": {
                "spots_remaining": 0
              },
              "template_id": "2-4-full"
            }
          },
          {
            "step": "2-5",
            "template_id": "2-5",
            "delay": "10d",
            "anchor": "enroll"
          }
        ],
        "on_complete": {
          "set_tag": "nurture",
          "enroll": "SEQ7"
        }
      },
      {
        "id": "SEQ3",
        "name": "Booked to show",
        "enroll_on": {
          "event": "call.booked"
        },
        "exit_on": [
          "call.completed",
          "call.cancelled",
          "call.no_show"
        ],
        "steps": [
          {
            "step": "3-1",
            "template_id": "3-1",
            "delay": "0m",
            "anchor": "enroll",
            "attach": "ics"
          },
          {
            "step": "3-2",
            "template_id": "3-2",
            "at": "call_time - 24h"
          },
          {
            "step": "3-3",
            "template_id": "3-3",
            "at": "call_time - 60m",
            "ignore_send_window": true
          }
        ],
        "on_event": {
          "call.no_show": {
            "enroll": "SEQ4"
          },
          "call.completed": {
            "route_by_outcome": {
              "undecided": "SEQ5",
              "not_fit": "SEQ5B",
              "closed": "none"
            }
          }
        }
      },
      {
        "id": "SEQ4",
        "name": "No-show",
        "enroll_on": {
          "event": "call.no_show"
        },
        "exit_on": [
          "call.booked",
          "email.replied"
        ],
        "steps": [
          {
            "step": "4-1",
            "template_id": "4-1",
            "delay": "45m",
            "anchor": "enroll"
          },
          {
            "step": "4-2",
            "template_id": "4-2",
            "delay": "2d",
            "anchor": "enroll"
          },
          {
            "step": "4-3",
            "template_id": "4-3",
            "delay": "5d",
            "anchor": "enroll"
          }
        ],
        "on_complete": {
          "set_tag": "nurture"
        }
      },
      {
        "id": "SEQ5",
        "name": "Post-call undecided",
        "enroll_on": {
          "event": "call.completed",
          "when": {
            "outcome": "undecided"
          }
        },
        "exit_on": [
          "deposit.paid",
          "email.replied"
        ],
        "steps": [
          {
            "step": "5-1",
            "template_id": "5-1",
            "delay": "2h",
            "anchor": "enroll"
          },
          {
            "step": "5-2",
            "template_id": "5-2",
            "delay": "2d",
            "anchor": "enroll"
          },
          {
            "step": "5-3",
            "template_id": "5-3",
            "delay": "5d",
            "anchor": "enroll"
          }
        ],
        "on_complete": {
          "set_tag": "nurture",
          "release_spot": true
        }
      },
      {
        "id": "SEQ5B",
        "name": "Not a fit",
        "enroll_on": {
          "event": "call.completed",
          "when": {
            "outcome": "not_fit"
          }
        },
        "steps": [
          {
            "step": "5b-1",
            "template_id": "5b-1",
            "delay": "2h",
            "anchor": "enroll"
          }
        ],
        "on_complete": {
          "set_tag": "nurture",
          "enroll": "SEQ7"
        }
      },
      {
        "id": "SEQ6",
        "name": "Client lifecycle",
        "enroll_on": {
          "event": "deposit.paid"
        },
        "exit_on": [],
        "side_effects_on_enroll": [
          {
            "set_tag": "client"
          },
          {
            "remove_tags": [
              "undecided",
              "inbound",
              "cold_prospect"
            ]
          }
        ],
        "steps": [
          {
            "step": "6-1",
            "template_id": "6-1",
            "delay": "0m",
            "anchor": "enroll",
            "attach": "agreement_pdf"
          },
          {
            "step": "6-2",
            "template_id": "6-2",
            "at": "film_date - 3d"
          },
          {
            "step": "6-3",
            "template_id": "6-3",
            "at": "film_date - 1d",
            "variant": {
              "when": {
                "event_seen": "balance.paid"
              },
              "template_id": "6-3-paid"
            }
          },
          {
            "step": "6-4",
            "template_id": "6-4",
            "on_event": "cut.delivered",
            "then": {
              "approval_window": "5d",
              "on_reply": {
                "create_task": {
                  "assignee": "emmanuel",
                  "title": "Revisions — {{business_name}}"
                }
              },
              "on_silence": {
                "emit": "cut.approved",
                "set_tag": "cut_approved"
              }
            }
          },
          {
            "step": "6-5",
            "template_id": "6-5",
            "at": "step[6-4].sent_at + 4d",
            "when": {
              "no_reply_since": "6-4"
            }
          },
          {
            "step": "6-6",
            "template_id": "6-6",
            "on_event": "episode.published"
          },
          {
            "step": "6-7",
            "template_id": "6-7",
            "at": "promo.started + 15d"
          },
          {
            "step": "6-8",
            "template_id": "6-8",
            "on_event": "promo.ended",
            "then": {
              "reminder": {
                "after": "5d",
                "when": {
                  "not": "debrief.booked"
                },
                "template_id": "6-8-reminder",
                "once": true
              }
            }
          }
        ]
      },
      {
        "id": "SEQ7",
        "name": "Monthly nurture (episode drops)",
        "enroll_on": {
          "event": "episode.published"
        },
        "audience": {
          "tags_any": [
            "nurture",
            "cold_closed"
          ],
          "not_in_active_sequence": true,
          "not_tag": [
            "do_not_contact"
          ]
        },
        "steps": [
          {
            "step": "7-1",
            "template_id": "7-1",
            "delay": "0m",
            "anchor": "enroll"
          }
        ]
      }
    ],
    "tasks_for_humans": [
      "Write specific_detail for every cold prospect before SEQ1 can enroll them",
      "Speed-to-lead call within 60 minutes of any lead.form_submitted",
      "Tag every call.completed with outcome + spot_number (+ reason fields for not_fit)",
      "Friday receipt pull: reach_number + reach_screenshot per live campaign (feeds 6-7)",
      "Flip edith_live to true only after a full dry-run log review"
    ],
    "reporting": {
      "daily_digest_to": "emmanuel_inbox",
      "fields": [
        "sent",
        "held (with reason)",
        "replies_routed",
        "bookings",
        "deposits",
        "no_shows",
        "sequence_exits"
      ]
    }
  },
  "templates": {
    "1-1": {
      "template_id": "1-1",
      "title": "Cold open",
      "trigger": "Day 0, within the send window",
      "subject": "{{business_name}} and the Charlotte Spotlight",
      "preview_text": "One question, then I'll get out of your way.",
      "body": "Hi {{first_name}} — quick one, and then I'll get out of your way.\n\n{{specific_detail}} That's how {{business_name}} ended up on our list.\n\nEmmanuel Bibbs — ten years shooting Charlotte — is filming the Charlotte Spotlight this fall: a monthly series of short films about the people behind up to ten local businesses. Every business keeps a produced commercial to run anywhere, forever, and we put the episode in front of the city.\n\nOne question: when someone in {{neighborhood}} finds out about you for the first time, what do they usually say?\n\nIf it's some version of \"I didn't know you were here,\" fifteen minutes with Emmanuel is worth it. He walks the board with you and tells you straight whether there's a spot that fits — or that there isn't.\n\n{{booking_link}}",
      "cta": "Book the 15-minute fit call",
      "internal_note": "{{specific_detail}} is one sentence a human wrote after looking at the business (a review, a detail from their page, their location). Empty = hold, don't send.",
      "merge_fields_used": [
        "business_name",
        "first_name",
        "specific_detail",
        "neighborhood",
        "booking_link"
      ]
    },
    "1-2": {
      "template_id": "1-2",
      "title": "The receipt",
      "trigger": "Day 3",
      "subject": "22,000 people for $77",
      "preview_text": "Not a projection. A screenshot.",
      "body": "{{first_name}} — it seems like the first note landed in a busy week, which is fair.\n\nHere's the one number worth your thirty seconds: the Omaha Spotlight reached more than 22,000 locals on its first $77 of promotion. Charlotte is the second city.\n\nTen spots per episode. Each business gets its own film, a commercial cut, and the episode promoted across the metro — and Emmanuel tells you which spot fits {{business_name}} in fifteen minutes.\n\nWould it be a bad idea to grab that call before the board fills?\n\n{{booking_link}}",
      "cta": "Book the fit call",
      "internal_note": "The \"would it be a bad idea\" question is Voss — a \"no\" is a yes. Keep it.",
      "merge_fields_used": [
        "first_name",
        "business_name",
        "booking_link"
      ]
    },
    "1-3": {
      "template_id": "1-3",
      "title": "Close the file",
      "trigger": "Day 7",
      "subject": "Should I close the file, {{first_name}}?",
      "preview_text": "No hard feelings either way.",
      "body": "{{first_name}} — I don't want to keep landing in your inbox if this isn't the season for {{business_name}}.\n\nShould I close your file? A one-word reply is fine either way, and if the timing's just off, say \"later\" and I'll check back when the next board opens.\n\n{{booking_link}}",
      "cta": "Reply (or book)",
      "internal_note": "Any reply routes to Emmanuel. \"Later\" = tag `nurture`, enroll in Sequence 7. No reply = tag `cold_closed`, no further sends.",
      "merge_fields_used": [
        "first_name",
        "business_name",
        "booking_link"
      ]
    },
    "2-1": {
      "template_id": "2-1",
      "title": "Speed to lead",
      "trigger": "Within 5 minutes of form submission",
      "subject": "Got your form — next step takes 2 minutes",
      "preview_text": "Emmanuel may also call you today.",
      "body": "{{first_name}} — got it. Thanks for filling that out.\n\nYou wrote: \"{{q5_answer}}\" That's exactly the kind of thing the Spotlight is built to say for you.\n\nNext step is a fifteen-minute fit call with Emmanuel. He'll ask about the business, walk the board with you, and tell you straight which spot fits — or if none does. Prices are already public on the board, so nothing on the call will surprise you: {{board_link}}\n\nGrab a time here: {{booking_link}}\n\nEmmanuel may also just call you today. If a Charlotte number rings, that's him.",
      "cta": "Book the fit call",
      "internal_note": "{{q5_answer}} = their answer to \"What would you want Charlotte to finally understand about your business?\" Trigger a task for Emmanuel: call within the hour.",
      "merge_fields_used": [
        "first_name",
        "q5_answer",
        "board_link",
        "booking_link"
      ]
    },
    "2-2": {
      "template_id": "2-2",
      "title": "The one question",
      "trigger": "Day 1",
      "subject": "The one question Emmanuel will ask you",
      "preview_text": "It decides which spot — if any.",
      "body": "{{first_name}} — it seems like you're wondering whether this actually works for a business like {{business_name}}.\n\nFair. So here's the question Emmanuel asks on every call: who's the face of the business, and are they willing to sit down for twenty minutes and talk about it?\n\nIf the answer is you — even reluctantly — you're a fit for a feature. If nobody wants to be on camera, there's still a spot; the film just gets built from the work itself.\n\nEither way, the call is where you find out. {{booking_link}}",
      "cta": "Book the fit call",
      "internal_note": "",
      "merge_fields_used": [
        "first_name",
        "business_name",
        "booking_link"
      ]
    },
    "2-3": {
      "template_id": "2-3",
      "title": "Proof",
      "trigger": "Day 3",
      "subject": "What the Omaha episode actually did",
      "preview_text": "Watch it — then decide.",
      "body": "{{first_name}} — before you decide anything, watch the original.\n\nThe Omaha Spotlight is the same format we're bringing to Charlotte: short films about the people behind everyday businesses. That first episode reached more than 22,000 locals on its first $77 of promotion. Not a projection — a screenshot Emmanuel will show you.\n\nHere's the episode: {{episode_link}}\n\nIf you'd want that for {{business_name}}, the fit call is fifteen minutes: {{booking_link}}",
      "cta": "Book the fit call",
      "internal_note": "{{episode_link}} = the Omaha original (https://youtu.be/wNylbkgS1mQ) until Charlotte Episode 1 exists, then Episode 1.",
      "merge_fields_used": [
        "first_name",
        "episode_link",
        "business_name",
        "booking_link"
      ]
    },
    "2-4": {
      "template_id": "2-4",
      "title": "The board is filling",
      "trigger": "Day 6",
      "subject": "{{spots_remaining}} spots left on the board",
      "preview_text": "Spots assign at payment. Nobody holds one.",
      "body": "{{first_name}} — straight update: {{spots_remaining}} of the ten spots are still open for this episode.\n\nSpots assign the moment a deposit clears, and Emmanuel doesn't hold them — for anyone. When this board fills, the next one opens next month, and the businesses on it get filmed then.\n\nWhat would need to be true for you to grab fifteen minutes this week? {{booking_link}}",
      "cta": "Book the fit call",
      "internal_note": "{{spots_remaining}} pulls live from the board. If 0, the engine sends 2-4-full instead.",
      "merge_fields_used": [
        "spots_remaining",
        "first_name",
        "booking_link"
      ]
    },
    "2-4-full": {
      "template_id": "2-4-full",
      "title": "Variant: board is full",
      "trigger": "Day 6, only when spots_remaining = 0",
      "subject": "This board's full — next one opens {{next_board_date}}",
      "preview_text": "You're first in line if you want it.",
      "body": "{{first_name}} — straight update: this episode's board filled.\n\nThe next one opens {{next_board_date}}, and the businesses on it get filmed that month. If you want {{business_name}} on it, grab fifteen minutes with Emmanuel now and you're first in line when it opens: {{booking_link}}",
      "cta": "Book the fit call",
      "internal_note": "",
      "merge_fields_used": [
        "next_board_date",
        "first_name",
        "business_name",
        "booking_link"
      ]
    },
    "2-5": {
      "template_id": "2-5",
      "title": "Graceful exit",
      "trigger": "Day 10",
      "subject": "Have you given up on this?",
      "preview_text": "Honest answer wanted. No pitch attached.",
      "body": "{{first_name}} — have you given up on the Spotlight for {{business_name}}?\n\nThat's a real question, not a guilt trip. If the answer is yes, reply \"yes\" and I'll stop. If it's \"not yet, just busy,\" reply that and I'll check back when the next board opens.\n\nIf it's \"actually, let's talk\" — {{booking_link}}",
      "cta": "Reply",
      "internal_note": "Exit ramp. No reply = tag `nurture`, enroll in Sequence 7. Any reply = Emmanuel.",
      "merge_fields_used": [
        "first_name",
        "business_name",
        "booking_link"
      ]
    },
    "3-1": {
      "template_id": "3-1",
      "title": "Confirmation",
      "trigger": "Immediately on booking",
      "subject": "You're on Emmanuel's calendar — {{call_time}}",
      "preview_text": "Fifteen minutes. Nothing to prepare.",
      "body": "{{first_name}} — locked in: {{call_time}} with Emmanuel.\n\nWhat it is: fifteen minutes. He asks about {{business_name}}, walks the board with you, and tells you straight which spot fits — or if none does.\n\nPrices are already on the board, so there are no surprises on the call: {{board_link}}\n\nNothing to prepare. Join here: {{call_link}}",
      "cta": "Add to calendar / join link",
      "internal_note": "Attach the .ics.",
      "merge_fields_used": [
        "call_time",
        "first_name",
        "business_name",
        "board_link",
        "call_link"
      ]
    },
    "3-2": {
      "template_id": "3-2",
      "title": "24-hour reminder",
      "trigger": "24 hours before call_time",
      "subject": "Tomorrow at {{call_time}} — one thing to have ready",
      "preview_text": "Just one.",
      "body": "{{first_name}} — tomorrow at {{call_time}}.\n\nOne thing to have ready: the answer to \"what do you want Charlotte to finally understand about {{business_name}}?\" You already wrote a version — Emmanuel will build from it.\n\nJoin here: {{call_link}}\n\nIf you need to move it, reply and I'll reschedule you.",
      "cta": "Show up (link)",
      "internal_note": "",
      "merge_fields_used": [
        "call_time",
        "first_name",
        "business_name",
        "call_link"
      ]
    },
    "3-3": {
      "template_id": "3-3",
      "title": "One-hour reminder",
      "trigger": "60 minutes before call_time",
      "subject": "In an hour — here's your link",
      "preview_text": "{{call_time}} with Emmanuel.",
      "body": "{{first_name}} — {{call_time}}, one hour out. Here's the link: {{call_link}}\n\nSee you shortly.",
      "cta": "Join",
      "internal_note": "",
      "merge_fields_used": [
        "call_time",
        "first_name",
        "call_link"
      ]
    },
    "4-1": {
      "template_id": "4-1",
      "title": "No stress",
      "trigger": "Within 1 hour of no-show",
      "subject": "Missed you — no stress",
      "preview_text": "Grab another time whenever works.",
      "body": "{{first_name}} — life happens; Emmanuel's run a business long enough to know.\n\nHere's the calendar whenever it works: {{rebook_link}}",
      "cta": "Rebook",
      "internal_note": "",
      "merge_fields_used": [
        "first_name",
        "rebook_link"
      ]
    },
    "4-2": {
      "template_id": "4-2",
      "title": "What you'd have heard",
      "trigger": "Day 2",
      "subject": "What you'd have heard on the call",
      "preview_text": "Fifteen minutes, one straight answer.",
      "body": "{{first_name}} — quick version of what the call is, in case it helps decide whether to rebook:\n\nEmmanuel asks about {{business_name}}, shows you the board, and tells you which spot fits — or that none does. Owners leave with a straight answer either way. Last week one of them left with a film date instead.\n\n{{rebook_link}}",
      "cta": "Rebook",
      "internal_note": "The \"last week\" line must be true. If it isn't yet, delete the sentence.",
      "merge_fields_used": [
        "first_name",
        "business_name",
        "rebook_link"
      ]
    },
    "4-3": {
      "template_id": "4-3",
      "title": "Close the file",
      "trigger": "Day 5",
      "subject": "Should I close your file?",
      "preview_text": "One word either way is fine.",
      "body": "{{first_name}} — it seems like now might not be the right time. Should I close your file?\n\nIf the timing's just off, reply \"later\" and I'll check back when the next board opens.\n\n{{rebook_link}}",
      "cta": "Reply",
      "internal_note": "No reply = tag `nurture`. \"Later\" = Sequence 7.",
      "merge_fields_used": [
        "first_name",
        "rebook_link"
      ]
    },
    "5-1": {
      "template_id": "5-1",
      "title": "Recap, same day",
      "trigger": "2 hours after call end",
      "subject": "Recap from today — Spot {{spot_number}}",
      "preview_text": "What Emmanuel recommended, in writing.",
      "body": "{{first_name}} — good talking with Emmanuel today. Here's the recap so you're not working from memory.\n\nHis read: {{business_name}} is a Spot {{spot_number}}. What that includes — your own film, your commercial cut, your place in the episode, the season promoted across the metro, and a walk-through of the numbers afterward.\n\nThe spot is $997: a $250 deposit claims it, the balance on film day. Spots assign at payment and nobody holds one — if it's gone when you're ready, the next open position is the offer.\n\nAnd the safety line: if the episode doesn't reach its filming floor, you choose — roll to the next season at the same spot and price, or every dollar back. It's in the agreement.\n\nDeposit here when you're ready: {{deposit_link}}",
      "cta": "Pay the deposit",
      "internal_note": "{{spot_number}} from Emmanuel's call outcome. If he recommended \"not a fit,\" Sequence 5b fires instead.",
      "merge_fields_used": [
        "spot_number",
        "first_name",
        "business_name",
        "deposit_link"
      ]
    },
    "5-2": {
      "template_id": "5-2",
      "title": "What would need to be true",
      "trigger": "Day 2",
      "subject": "What would need to be true?",
      "preview_text": "One honest question.",
      "body": "{{first_name}} — it seems like you're weighing whether the Spotlight is the right spend for {{business_name}} right now.\n\nSo — what would need to be true for it to make sense?\n\nIf the hesitation is \"that's a lot for a short segment,\" the reframe Emmanuel would give you: you're not buying seconds. You're buying position in a season the city sees, a produced commercial you own and run as your own ad, and someone showing you afterward what the attention did.\n\nIf the hesitation is something else, reply and tell me — that's what I'm here for.\n\n{{deposit_link}}",
      "cta": "Reply (or deposit)",
      "internal_note": "",
      "merge_fields_used": [
        "first_name",
        "business_name",
        "deposit_link"
      ]
    },
    "5-3": {
      "template_id": "5-3",
      "title": "Different direction?",
      "trigger": "Day 5",
      "subject": "Different direction?",
      "preview_text": "Either answer helps us plan the board.",
      "body": "{{first_name}} — have you decided to go a different direction on Spot {{spot_number}}?\n\nEither way, I'd like to know so Emmanuel can plan the board. If it's a yes, the deposit link still works: {{deposit_link}}\n\nIf it's a no, thanks for the time — and I'll let you know when the next board opens.",
      "cta": "Reply",
      "internal_note": "No reply = tag `nurture`, spot released to the board. Any reply = Emmanuel.",
      "merge_fields_used": [
        "first_name",
        "spot_number",
        "deposit_link"
      ]
    },
    "5b-1": {
      "template_id": "5b-1",
      "title": "Not a fit (Sequence 5b, one email)",
      "trigger": "2 hours after call end",
      "subject": "Straight answer, as promised",
      "preview_text": "Why, and what would change it.",
      "body": "{{first_name}} — Emmanuel said he'd give you a straight answer, so here it is in writing: {{business_name}} isn't a fit for this board.\n\nThe reason: {{not_fit_reason}}\n\nWhat would change it: {{what_would_change}}\n\nYou'll hear from me when the next board opens. In the meantime, thanks for the fifteen minutes — you were straight with us too.",
      "cta": "None",
      "internal_note": "Both merge fields come from Emmanuel's outcome note. Empty = hold for human. Tag `nurture`.",
      "merge_fields_used": [
        "first_name",
        "business_name",
        "not_fit_reason",
        "what_would_change"
      ]
    },
    "6-1": {
      "template_id": "6-1",
      "title": "Welcome + timeline",
      "trigger": "Immediately on deposit",
      "subject": "Spot {{spot_number}} is yours — the whole timeline",
      "preview_text": "Film date, delivery, episode, promotion, numbers.",
      "body": "{{first_name}} — welcome to the season. Spot {{spot_number}} is yours; {{business_name}} is on the board.\n\nHere's the whole timeline in one place:\n- Film day: {{film_date}} — the $747 balance is due that day\n- Your cut delivered: within a few days of filming. You get five days for one round of tweaks\n- Episode {{episode_number}} releases, then the season promotion runs for a month\n- Your numbers: I'll send them mid-flight, and Emmanuel walks you through the full picture afterward\n\nNext thing you'll get from me: the prep note a few days before film day.",
      "cta": "None",
      "internal_note": "Attach the agreement countersigned copy. film_date from Emmanuel's close notes.",
      "merge_fields_used": [
        "spot_number",
        "first_name",
        "business_name",
        "film_date",
        "episode_number"
      ]
    },
    "6-2": {
      "template_id": "6-2",
      "title": "Prep note",
      "trigger": "3 days before film_date",
      "subject": "Film day {{film_date}} — what to expect",
      "preview_text": "Give the team a heads-up. Cameras make people weird.",
      "body": "{{first_name}} — film day is {{film_date}}.\n\nWhat to expect: Emmanuel is on site about a morning. Give the team a heads-up — cameras make people weird for ten minutes and then everyone forgets he's there.\n\nWear what you'd wear on your best workday; solid colors beat patterns. Have the space looking like you'd want the city to see it.\n\nYou'll sit down for about twenty minutes of conversation — no memorizing anything, just you talking about {{business_name}}.",
      "cta": "None",
      "internal_note": "",
      "merge_fields_used": [
        "film_date",
        "first_name",
        "business_name"
      ]
    },
    "6-3": {
      "template_id": "6-3",
      "title": "Day-before",
      "trigger": "1 day before film_date",
      "subject": "Tomorrow — balance link and one reminder",
      "preview_text": "$747 due on film day. Team heads-up done?",
      "body": "{{first_name}} — tomorrow's the day.\n\nThe $747 balance is due on film day; here's the link so it's one less thing: {{balance_link}}\n\nOne reminder: tell the team a camera's coming. It goes better when nobody's surprised.",
      "cta": "Pay the balance",
      "internal_note": "If balance.paid was already seen, the engine sends 6-3-paid instead.",
      "merge_fields_used": [
        "first_name",
        "balance_link"
      ]
    },
    "6-3-paid": {
      "template_id": "6-3-paid",
      "title": "Variant: balance already paid",
      "trigger": "1 day before film_date, only when balance.paid seen",
      "subject": "Tomorrow — you're all set",
      "preview_text": "One reminder for the team.",
      "body": "{{first_name}} — tomorrow's the day, and you're paid up. Nothing to do.\n\nOne reminder: tell the team a camera's coming. It goes better when nobody's surprised.",
      "cta": "None",
      "internal_note": "",
      "merge_fields_used": [
        "first_name"
      ]
    },
    "6-4": {
      "template_id": "6-4",
      "title": "Cut delivered",
      "trigger": "Event `cut.delivered`",
      "subject": "Your cut is ready — 5 days for tweaks",
      "preview_text": "One round. Factual fixes, trims, on-screen text.",
      "body": "{{first_name}} — your cut is ready: {{cut_link}}\n\nYou have five days for one round of tweaks — factual corrections, trims, on-screen text. Reply with them in one list and Emmanuel handles it.\n\nIf I don't hear from you in five days, it's approved as-is and heads into the episode. Kindly said: silence is a yes.",
      "cta": "Reply with revisions (or nothing)",
      "internal_note": "Approval window = 5 days from send. Reply = task for Emmanuel. No reply at day 5 = auto-approve, tag `cut_approved`.",
      "merge_fields_used": [
        "first_name",
        "cut_link"
      ]
    },
    "6-5": {
      "template_id": "6-5",
      "title": "Last day for tweaks",
      "trigger": "Day 4 after 6-4, only if no reply",
      "subject": "Last day for tweaks",
      "preview_text": "Tomorrow it locks.",
      "body": "{{first_name}} — tomorrow your cut locks and goes into the episode.\n\nIf there's anything to fix, reply today in one list. If it's good as-is, do nothing — that's a yes.\n\n{{cut_link}}",
      "cta": "Reply (or nothing)",
      "internal_note": "",
      "merge_fields_used": [
        "first_name",
        "cut_link"
      ]
    },
    "6-6": {
      "template_id": "6-6",
      "title": "You're live",
      "trigger": "Event `episode.published`",
      "subject": "You're live — Episode {{episode_number}}",
      "preview_text": "Watch, share, and run your commercial.",
      "body": "{{first_name}} — Episode {{episode_number}} is live, and {{business_name}} is in it: {{episode_link}}\n\nTwo things worth doing today:\n1. Share the episode — tag Creative Impact and we'll push it from our side.\n2. Run your commercial cut. It's yours; your page, your ads, your website. The businesses that get the most out of this are the ones whose cut is already running when the promotion starts.\n\nThe season promotion runs for the next month. I'll send your numbers mid-flight.",
      "cta": "Watch/share the episode",
      "internal_note": "",
      "merge_fields_used": [
        "episode_number",
        "first_name",
        "business_name",
        "episode_link"
      ]
    },
    "6-7": {
      "template_id": "6-7",
      "title": "Mid-flight numbers",
      "trigger": "Day 15 of the promotion window",
      "subject": "Mid-season numbers, straight from the dashboard",
      "preview_text": "Reach so far, screenshot attached.",
      "body": "{{first_name}} — mid-flight, straight from the dashboard: the season has reached {{reach_number}} people so far. Screenshot attached: {{reach_screenshot}}\n\nFull walk-through with Emmanuel once the month closes. Nothing to do today.",
      "cta": "None",
      "internal_note": "reach_number and screenshot come from the Friday receipt pull. Empty = hold.",
      "merge_fields_used": [
        "first_name",
        "reach_number",
        "reach_screenshot"
      ]
    },
    "6-8": {
      "template_id": "6-8",
      "title": "Debrief invite",
      "trigger": "Event `promo.ended`",
      "subject": "Your numbers are in — 20 minutes with Emmanuel",
      "preview_text": "The real picture, and one recommendation.",
      "body": "{{first_name}} — the promotion month is done and your numbers are in.\n\nEmmanuel does a twenty-minute debrief with every business on the board: what the season reached, what it did for {{business_name}}, and one recommendation for what to run next. No pitch — a recommendation.\n\nGrab a time: {{debrief_link}}",
      "cta": "Book the debrief",
      "internal_note": "If not booked in 5 days, the engine sends 6-8-reminder once, then stops.",
      "merge_fields_used": [
        "first_name",
        "business_name",
        "debrief_link"
      ]
    },
    "6-8-reminder": {
      "template_id": "6-8-reminder",
      "title": "Debrief, one reminder",
      "trigger": "5 days after 6-8, only if debrief not booked",
      "subject": "Twenty minutes — still open",
      "preview_text": "Your season numbers, walked through.",
      "body": "{{first_name}} — Emmanuel's debrief slots for this season close soon, and yours is still open.\n\nTwenty minutes: what the season reached, what it did for {{business_name}}, one recommendation. {{debrief_link}}\n\nIf you'd rather skip it, no problem — your cut is yours to run either way.",
      "cta": "Book the debrief",
      "internal_note": "",
      "merge_fields_used": [
        "first_name",
        "business_name",
        "debrief_link"
      ]
    },
    "7-1": {
      "template_id": "7-1",
      "title": "Episode drop",
      "trigger": "Day of episode publish",
      "subject": "Episode {{episode_number}} is live — {{featured_count}} Charlotte businesses",
      "preview_text": "Watch it. The next board is open.",
      "body": "{{first_name}} — Episode {{episode_number}} of the Charlotte Spotlight just dropped: {{featured_count}} local businesses, the people behind them, and the reasons their regulars already know.\n\nWatch it here: {{episode_link}}\n\nThe next board is open. If {{business_name}} should be in the next one, fifteen minutes with Emmanuel is where that starts: {{booking_link}}",
      "cta": "Watch (booking link secondary — the only exception to one-link, because the watch IS the value)",
      "internal_note": "Unsubscribe footer required on this one; it's list mail.",
      "merge_fields_used": [
        "episode_number",
        "featured_count",
        "first_name",
        "episode_link",
        "business_name",
        "booking_link"
      ]
    }
  },
  "signature": "EDITH\nCreative Impact · Emmanuel's assistant — the AI kind. A human reads every reply.\nhello@creativeimpactmedia.co",
  "source_hash": "02e6c63959081fa1",
  "warnings": [
    "2-1: 2 links in the body (gate: one CTA)",
    "2-3: 2 links in the body (gate: one CTA)",
    "2-4-full: subject is 54 characters before merge (gate: under 50)",
    "3-1: 2 links in the body (gate: one CTA)",
    "3-2: subject is 51 characters before merge (gate: under 50)",
    "7-1: subject is 76 characters before merge (gate: under 50)"
  ]
};
